name: Build Kairos Cloud Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v1
    with:
      version: "v4.2.0"
      model: "generic"
      arch: "arm64"
      iso: true
      cloud_config: "cloud-config.yaml"
      compute_checksums: true
      summary_artifacts: true
